### PR TITLE
Adding the availability of mobile applications with Moqui

### PR DESCRIPTION
**Pull request by ghost**
Hi David, since this is not really a 'add-in' I explained it just in the company description if you do not mind.

### CODE REVIEW

**Comment by growerp** [comment]
url correction

**Comment by jonesde** [comment]
Hi Hans, the Service Providers page is really meant for services and not products, whereas the /addons.html page is meant for 'products' that use Moqui. The page currently has two sections: 'Add-on Component Directory' and 'Web Sites built with Moqui'. 

The GrowERP component would make sense in the first section, and I agree that client applications that talk to a Moqui server but are not Moqui 'components' would make more sense in a separate section, perhaps labelled as simply as 'Client Applications' with the same columns as the Add-on Component Directory section.

BTW, I'm hoping these will have much more in them over time, and even change those pages to be database driven and have request forms for easier submission and moderation.

**Comment by growerp** [comment]
ok david another try....hopefully this fits better?

**Comment by jonesde** [comment]
This does look better Hans. Just a couple of things stand out:

1. the title "Independent clients such as mobile applications using Moqui as a backend REST server" is really long... something like "Client Applications" is much shorter and (to me anyway) seems adequate for define a category

2. I'd prefer to not have the google and apple play store images in our repo and served through moqui.org, there might even be legal issues with that, aren't those hosted by Google and Apple somewhere? If not we should use plain text links with no images, I'm not keen on having those files in there or doing the legal research for each to make sure Google and Apple are okay with it.

I'd be fine merging this and changing the title, but the image binary files need to be removed and replaced by a URL where they are hosted elsewhere, or changed to text links.

**Comment by growerp** [comment]
not sure if you can see this, but changed according your requests

**Comment by jonesde** [comment]
Looks good overall, some types in there, I'll adjust after merge

**Comment by jonesde** [comment]
The site is now updated with these changes.

**Comment by growerp** [comment]
Thanks David!

**Pull request merged**
